### ISSUE TITLE
Stricter type checking / IntelliSense 

### ISSUE THREAD

**Issue by claytercek** [bluecadet/launchpad#117]
Mentioned in our plugin API discussion (#114)

One of the large benefits of moving to JS configs instead of JSON is intelliSense, but launchpad is not currently equipped to take advantage of that. The JS Language service looks for typescript declaration files (`.d.ts`) for intellisense in most IDEs, but because launchpad is written in JS, no declaration files are being generated. 

What we can do is add a `tsconfig.json` file to each of the launchpad package directories, and configure them with the following options: 

```jsonc
{
  // ...
  "compilerOptions": {
    // ...
    "allowJs": true,
    "checkJs": true,
    "declaration": true,
    "emitDeclarationOnly": true,
    // ...
  },
  "include": ["**/*.js"]
  // ...
}
```

Then add a `tsc` step to the changeset publish action. This will run the ts type-checker on our js + jsdoc, generating declaration files and publishing them alongside the js to npm. 

This also has the added benefit of more thorough type checking across the board.

**Comment by benjaminbojko** [comment]
Love this idea! I was wondering a few times what it would take to generate these. Might also help with private vs public functions down the road, right?

Seems like a pretty low-hanging fruit feature to try out as. Marking it as medium priority.

**Comment by claytercek** [comment]
Strict type checking has been added with PR #118, breaking config intellisense into a separate ticket
