### ISSUE TITLE
yargs `--version` option always returns `0.0.1`

### ISSUE THREAD

**Issue by claytercek** [bluecadet/launchpad#123]
If you run `npx launchpad --version` it will always output `0.0.1`. Yargs defaults to the version in the package.json, but it looks like it's using the root package.json rather than the package.json in `packages/launchpad`.

**Comment by claytercek** [comment]
this might just be when developing locally using `npm link` – will have to do some more testing

**Comment by benjaminbojko** [comment]
Interesting! Can confirm that this only happens when linking launchpad locally with my setup:

Linked repo:
```
npx launchpad --version
0.0.1
```

After running `npm unlink --no-save launchpad` in the same directory:
```
npx launchpad --version
1.0.0
```

**Comment by claytercek** [comment]
Oh cool, closing 👍
