### ISSUE TITLE
Intellisense for configs

### ISSUE THREAD

**Issue by claytercek** [bluecadet/launchpad#125]
Now that JS configs are implemented (#124) and we have type checking (#117 #118) we can add intellisense to the config files.

There are two popular ways to do this that I'm aware of:

1. a function that just returns the first argument (which is typed)
  ```js
  import { defineConfig } from '@bluecadet/launchpad';
  
  export default defineConfig({
     // ...
  })
  ```

2. using jsdoc `@type` annotation
  ```js
  /** @type {import('@bluecadet/launchpad').LaunchpadConfig} */
  export default {
     // ...
  }
  ```

It should be pretty easy to support both, but I'm particularly fond of the first one, as that enables us to more easily accept a callback for the config argument and pass context later down the line if we want:

```js
import { defineConfig } from '@bluecadet/launchpad';

export default defineConfig((ctx) => ({
   // ...
   property: ctx.env.EXAMPLE_ENV_VARIABLE
   // ...
}))
```

**Comment by benjaminbojko** [comment]
Agreed! First option seems preferable and I like the option for a callback.

Is the naming and pattern of `defineConfig()` something you've seen in the past? My head is still stuck in OOP land and I imagined exporting an instance of a `Config` object, that could or could not be extended. But my understanding from your other PR is that this would support autocompletion because the return type of `defineConfig` would be `Config`, right? So that would eliminate the need to explicitly call `new Config({...})`?

**Comment by claytercek** [comment]
Yeah, `defineConfig()` is used by [sanity](https://www.sanity.io/docs/config-api-reference), [vite](https://vitejs.dev/config/), [astro](https://docs.astro.build/en/guides/configuring-astro/). I've also seen the latter pattern (`@type import(...)`) used by [tailwind](https://tailwindcss.com/docs/installation/using-postcss), [sveltekit](https://kit.svelte.dev/docs/configuration), [nextjs](https://nextjs.org/docs/pages/api-reference/next-config-js).

The defineConfig function would look something like this in js/jsdoc
```js
/**
 * @param {Config} config 
 * @returns {Config}
 */
function defineConfig(config) {
	return config;
}
```
Because the parameter has a defined type, users would see intellisense hints and autocomplete when populating that parameter, similar to how they would get hints when populating `new Config([param])` only if the `Config` class constructor parameter is typed. 

We could definitely use a Config class as the default export, but that does have the small downside of duplication in documentation that was mentioned in #118:

```js
class Config {
  /** 
   * @type {string} this type can only be seen when accessing the property on a Config instance
   */
  foo;

  /**
   * @param {object} options
   * @param {string} options.foo this type can only be seen when constructing a new Config instance with `new Config({ foo: 'bar' })`
   */
  constructor({
    foo
  }) {
    this.foo = foo;
  }
}

// vs

/**
 * @typedef Config
 * @property {string} foo this type and description can be seen when constructing and when accessing an object with type `Config`
 */

```

**Comment by benjaminbojko** [comment]
Thanks for the breakdown!

I like the simplicity of `defineConfig()`, and that there's no additional type descriptions needed. 

What I like about the import method is that it feels a bit more freeform and makes the syntax of the file itself just a tad more legible and straightforward.

But you make a really good point about documentation, so let's go with the `defineConfig()` approach! 💯
