### ISSUE TITLE
Move detailed docs to vitepress 

### ISSUE THREAD

**Issue by claytercek** [bluecadet/launchpad#131]
Discussed in #116 

- Move detailed docs to vitepress, build to github pages
- re-implement autogenerated docs from JSDoc comments (broken by #118)

**Comment by claytercek** [comment]
@benjaminbojko Looks like reimplementing the autogenerated docs will be a bit more difficult than anticipated. There are a couple of approaches, but none seem to fully match our needs:
- use the TS compiler to manually extract the type info from a given file, then pass that json to vitepress and display with custom components. Here's an example that shows how one can get the constructor info from the classes in a file as json: https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API#using-the-type-checker – this gets complicated, as JSDoc isn't included in the AST
- use [typedoc](https://typedoc.org/) to generate a JSON file with all type info for the whole repo, then collect the relevant  json from that larger set and pass it to vitepress to be rendered via custom components. This is pretty unwieldy - just for the content package, it dumps out 25k lines of JSON, with types fragmented across the whole thing. 

Overall both options could potentially work, but getting either setup will take a good chunk of time. I'm not sure that the benefit of automation here outweighs the cost of dev and maintenance when compared to just manually writing up the markdown files.

**Comment by benjaminbojko** [comment]
Oof yeah. It was nice to have all the various options listed out, but the main challenge with our docs is actually making it clear how to fit all the pieces together.

I think with #116 and the new config autocomplete, we can probably make the documentation more focused on use cases, principles, etc. Let's close this one as won't fix.

**Comment by benjaminbojko** [comment]
Whoops realized that this was the larger vitepress issue and not just for jsdocs :)

We should continue with vitepress, but remove all dependencies to jsdocs (scripts, templates, etc).

**Comment by claytercek** [comment]
Resolved by #179
