### ISSUE TITLE
`re2` (used by `get-urls` package) takes 2 minutes to install?

### ISSUE THREAD

**Issue by claytercek** [bluecadet/launchpad#134]
The package `re2` takes 2+ minutes to install, noticeable on mac and windows. We're using it via the `get-urls` package in launchpad content, maybe we should look into an alternative that doesn't use re2?

**Comment by benjaminbojko** [comment]
Thanks for identifying that! I'm definitely open to exploring alternatives. We haven't used custom JSON endpoints in a while, but I'd want to make sure that whatever alternative we find is somewhat en-par with `get-urls`. I'm open to that being just a really good regex, that maybe could be customized via options.
