### ISSUE TITLE
Implement rolling logs for PM2

### ISSUE THREAD

**Issue by benjaminbojko** [bluecadet/launchpad#2]

**Comment by claytercek** [comment]
whoops closed by mistake

**Comment by benjaminbojko** [comment]
A couple more thoughts after digging into this again: What you described is pretty much the conundrum that we're in with PM2 and log rotation. The main reason I ended up tailing log files by default for apps is that I haven't quite been able to get a good handle of how to deal with bus events.

Bus logs seem to be coming from a stream that is only periodically flushed. Multiple log messages are batched together, and then separated by additional empty lines:

![image](https://user-images.githubusercontent.com/295789/200077611-0e8489a9-77b6-4b19-ab7e-403324719060.png)

I assume this has to do with how PM2 flushes its own stream buffer periodically and that's causing quite a few issues:

- The obvious one is cosmetic, since it's hard to tell which log might be a single line message vs multiple lines.
  - In theory this could easily be fixed by splitting everything by `\r\n`, but that seems like it would have other side effects.
  ```js
  const lines = (event.data || '').split('\r\n');
  for (const line of lines) {
     this._logger.info(line);
  }
  ```
  ![image](https://user-images.githubusercontent.com/295789/200078241-03fba1db-a856-4a08-aacc-6808930881a2.png)
- A more severe issue is when an app logs both to `stdout` and `stderr`. E.g. in Cinder, the order of logs occasionally gets mixed up (an error might appear before or after an info log, regardless of the order in code), rendering them pretty much useless for debugging.
  - See how the 3 error outputs appear in between info and warning? The sequence should be info, warning, error instead: ![image](https://user-images.githubusercontent.com/295789/200074492-488af4af-7930-4963-97bf-2dabcd045be0.png)
  - Another hack for this is to only stream messages via `stdout` and ignore `stderr` for application logs, but that's not consistent with how PM2 routes logs to files (they get separated for `stdout` and `stderr`, and they appear in order). It is, however, how Unity handles logs (they all go to a single destination).
- Unity spits out a bunch of meta info at the beginning that it doesn't include in file logs. Not a big deal IMHO, but it does bloat the logs a bit and they also come in asynchronously: 
![image](https://user-images.githubusercontent.com/295789/200078450-6c3e92ae-8180-4e43-93ed-1c2ee9005c2c.png)

I'll revisit this again, but after this deep-dive I recalled exactly why I went the current route. Doesn't mean there's no better way, just have to find the right parts to hook into...

**Comment by claytercek** [comment]
I've been experimenting a bit with bus logs, tailing, logging to named pipes, unix fifo special files, and I think the best option here is to just make bus logging the default and tailed logs an opt-in feature (with the caveat that they can't be rotated).

Regarding the issues above:
> The obvious one is cosmetic, since it's hard to tell which log might be a single line message vs multiple lines.
> - In theory this could easily be fixed by splitting everything by \r\n, but that seems like it would have other side effects. 

I think splitting by carriage return here is pretty safe, considering that's basically what [Tail is doing (see the `separator` paramater)](https://github.com/lucagrulla/node-tail#constructor-parameters). We could use the same regex to split too. 

> A more severe issue is when an app logs both to stdout and stderr. E.g. in Cinder, the order of logs occasionally gets mixed up (an error might appear before or after an info log, regardless of the order in code), rendering them pretty much useless for debugging. 

I actually see the same issue when using the default tail behavior. I also noticed that this happens less frequently with bus logging when the `out_file` and `error_file` are set to `/dev/null` and tailing is disabled. Still trying to figure out if there's a more solid solution for this, but mostly just wanted to note that Tail is also afflicted. 

> Unity spits out a bunch of meta info at the beginning that it doesn't include in file logs. Not a big deal IMHO, but it does bloat the logs a bit and they also come in asynchronously

yeah can't figure out a workaround for this one. We could do something hacky like manually surpressing messages that begin with [UnityMemory]?

**Comment by claytercek** [comment]
Yep! That's all spot on. 

There were basically zero advantages for the fifo approach over the bus, and it introduces a lot more room for bugs and errors with file reading/streaming.
