### ISSUE TITLE
Testing: CI or Github Actions

### ISSUE THREAD

**Issue by pingevt** [bluecadet/launchpad#37]
Add testing to Github Actions, so we can see test results for PRs and also not rely on local testing only

**Comment by benjaminbojko** [comment]
@pingevt could you add a description for this ticket?

**Comment by pingevt** [comment]
If we release this to the public, we may want to add this sooner than later. Bumping priority to medium

**Comment by benjaminbojko** [comment]
Sounds good! Do you already have any thoughts on what to test and how? I've been shying away from it just given the number of dependencies and use cases.

**Comment by pingevt** [comment]
HA - yea, I've been afraid of that list as well. I haven't really done testing in Node env either.

I think the first step is just "how is this setup"? Can we unit test or do we need full functional testing - or both? And just like the documentation, we make sure we check it off when we submit a PR.

Some of the util classes I could see adding unit tests. But for the most part I think we need functional tests.
 
From My perspective on the content side, I'd love to have test coverage on all the sources and all the config variables we're using so we can easily see breaking changes. With everything here though, let's start small, and add in as we can.

The JSON source is pretty simple and we can start there as an actual test.

**Comment by claytercek** [comment]
Resolving – with #179, we have lint tests, monorepo dependency tests, and vitest unit tests!
