### ISSUE TITLE
Should we stop supporting Airtable?

### ISSUE THREAD

**Issue by pingevt** [bluecadet/launchpad#49]
I think we are being discouraged to use airtable. So should we stop supporting it?

**Comment by benjaminbojko** [comment]
Can you elaborate on the reasons why people are pushing against it? I have my own but am curious.

Internally, if we have the choice between Sanity or Airtable, we should definitely go with Sanity. I've still heard from clients that they like using it and I think continuing to support the package at its current state would be great. We can keep it a low priority to add new features/keep parity with the other sources, though. It's a nice scratchpad for non-technical folks to set up data, so imo it's worth keeping around for a bit longer.

**Comment by pingevt** [comment]
I don't have anything official, but seems price. Maybe this was an internal thing 🤷  But I think you answered the question. Closing for now!
