### ISSUE TITLE
Move credentials.json to .env file

### ISSUE THREAD

**Issue by benjaminbojko** [bluecadet/launchpad#53]
This should align more with best practices for storing sensitive info and dealing with test/live environments.

Need to consider possible backwards compatibility with:
- `credentials.json`
- Command line parameters
- `launchpad.json` config parameters

Also should think about whether there's a global credentials/sensitive info manager class or just one for content sources.

cc @pingevt

**Comment by benjaminbojko** [comment]
See #18

**Comment by claytercek** [comment]
Copied from #126:

Now that we have JS configs, I imagine it would make sense to load in dotenv files for easier and gitignore-able config customization.

We have some logic in ConfigManager to search for the nearest launchpad config in the CWD and parent directories. Once the config is found, we can look for the `.env` files alongside it.

---

It could be nice to also add an extra option to the launchpad CLI to allow selecting specific dotenv files, and perhaps cascade them. Example:

Given the following dotenv files (assuming files ending in `.local` are gitignored):

```
# .env
API_DATASET="production"
PC_NAME="foo"
HELLO="world"

# .env.local
PC_NAME="bar"

# .env.development
API_DATASET="development"
```

Running `npx launchpad` would load `.env` then load `.env.local`, resulting in  
```json
{
   "API_DATASET": "production",
   "PC_NAME": "bar",
   "HELLO": "world"
}
```

Running `npx launchpad -e development` would load `.env` then load `.env.local` then `.env.development`, resulting in  
```json
{
   "API_DATASET": "development",
   "PC_NAME": "bar",
   "HELLO": "world"
}
```

--- 

This feature could potentially replace `credentials.json` too, as users could put API credentials in a gitignored dotenv file then reference them in the config, _plus_ the cascading logic above allow for more flexibility.
