### ISSUE TITLE
Allow imageTransforms to use any of sharp's image ops

### ISSUE THREAD

**Issue by benjaminbojko** [bluecadet/launchpad#66]
- Do a simple lookup of option key to functions available to [sharp's image operations API](https://sharp.pixelplumbing.com/api-operation)
- Pass the value for that key as the parameter to sharp's function (if it exists)
- Infer the filename from a list of all parameter values (perhaps special consideration for primitive values vs objects, and certain properties like width/height)

**Comment by claytercek** [comment]
done with #179
