### ISSUE TITLE
Some Scaffold scripts fail in powershell 7

### ISSUE THREAD

**Issue by igierard** [bluecadet/launchpad#94]
When running Scaffold in Powershell 7 (vs the windows built in "Windows Powershell") some elements fail.

Particularly the enable/disable services calls seem to fail. This seems to be the result of Get-WmiObject being deprecated in powershell 7.

**Comment by benjaminbojko** [comment]
Fixed in #95 and now live on NPM with Launchpad version [1.3.9](https://github.com/bluecadet/launchpad/releases/tag/%40bluecadet%2Flaunchpad%401.3.9), scaffold version [1.6.0](https://github.com/bluecadet/launchpad/releases/tag/%40bluecadet%2Flaunchpad-scaffold%401.6.0)
